### PR TITLE
Add Ipv6 support #18

### PR DESCRIPTION
**Pull request by robertcsakany**

### CODE REVIEW

**Comment by robertcsakany** [comment]
> Does enabling the link-local address also make it listen for router advertisements and such to obtain a global IPv6 address?

Global and Local.

> I see that the MQTT library currently doesn't support IPv6, 

I see the documentation the host handled as Ipv4 host. I will investigate on MQTT Client lib....

> so what's the use-case for adding IPv6? What can you do with it expect ping?

The logging function I'm working on will support Ipv4 / Ipv6. And I think its better to preare that in the near future it will be supportted in mqtt client as well.

**Comment by shmuelzon** [comment]
> The logging function I'm working on will support Ipv4 / Ipv6. And I think its better to preare that in the near future it will be supportted in mqtt client as well.

I’m already working on this and have a basic version ready. I’ll make sure it’s IPv6 ready.

The problem right now with this pull request is that the app is notified only upon getting an IPv4 address. If logging and/or MQTT will be IPv6 the connection might fail if we don’t have an address yet.
May I suggest altering the code to wait for an IPv4 address or a non link-local IPv6 address. Set some timer to wait for the other (maybe arround 1 second, not sure how long it takes to get an IPv6 address) and only once the timer is invoked or the second IP address was set do we notify the app so it can continue.
Does that sound reasonable to you or do you have any reservations?

**Comment by robertcsakany** [comment]
> May I suggest altering the code to wait for an IPv4 address or a non link-local IPv6 address
There is no any IPv6 address without link-local.  All IPv6 enabled interfaces have a link-local unicast address.

I've already thinked about the IP / Network events and how handle it. Have to keep in mind there can be new events which can change the service resolution mechanism. (for example mDNS). So there are several network/resolve events can trigger the service state changes. When the system is ready to serve? 
I think all of internal services connections have to be managed in a central service, which will trigger actual service with the resolved address info.

So when we got  a SYSTEM_EVENT_STA_GOT_IP or SYSTEM_EVENT_STA_GOT_IP6 have to retry the resolution of the missing services - I think when we got IPV4 address and the service is resolvable on IPV4/IPV6 too, on that case its not a problem that IPV4 version is resolved and not IPV6. And when SYSTEM_EVENT_STA_LOST_IP or SYSTEM_EVENT_STA_DISCONNECTED event come have to gracefully shutdown services so the next time when connection OK again the init can be recalled.

There is a **service_connection_def**  struct with the following fields:

**name** - the service name - for examle mqtt, udp-log, ota
**get_supported_mechanisms** - some flags: IPv4, IPv6, mDNS... which we define which method are supported with the given service - there can be added new ones, I don't think that there will be more than that 3, but who knows. 
**get_host** - a method pointer which return a char array with the host address.
**on_resolved** - a method pointer when the central resolution service get an address call it. I suggest using of sockaddr_storage struct because it can be IPV4/ IPV6 address too.
**on_lost** - a method pointer which called when disconnection happens
**is_ok** - a method pointer which can be called to check the serice not only host resolution problems happens, inside the implementation - for example auth error happens the service itself cannot work.

Because services can based other services states - for example BLE2MQTT when send a message have to check that mqtt is okay. Maybe with an event mechanism that can decoupled.

What do you think?

**Comment by shmuelzon** [comment]
To me, this seems like an extreme overkill...

I've decided to hold off IPv6 for now until I have better idea how to deal with it (and add IPv6 in my own network to test it).
Anyways, it doesn't make sense to enable IPv6 without MQTT supporting it so I'm closing the PR for now. I'll revisit it, hopefully, in the near future.

**Pull request closed without merging**
