### PR TITLE
Handle write no response

### PR DESCRIPTION
**Pull request by DurandA**

### CODE REVIEW

**Comment by shmuelzon** [comment]
Thanks for this.

Doesn't supporting write with no response also means we need to call `esp_ble_gattc_write_char()` with `ESP_GATT_WRITE_TYPE_NO_RSP` instead of `ESP_GATT_WRITE_TYPE_RSP` at [main/ble.c:144](https://github.com/shmuelzon/esp32-ble2mqtt/blob/83b868c5bb2e5713fe71d518cd3040412951fb8b/main/ble.c#L144)?

**Comment by DurandA** [comment]
> Doesn't supporting write with no response also means we need to call `esp_ble_gattc_write_char()` with `ESP_GATT_WRITE_TYPE_NO_RSP` instead of `ESP_GATT_WRITE_TYPE_RSP` at [main/ble.c:144](https://github.com/shmuelzon/esp32-ble2mqtt/blob/83b868c5bb2e5713fe71d518cd3040412951fb8b/main/ble.c#L144)?

I missed it since the value was written successfully written (even if the characteristic is only _WRITE NO RESPONSE_) without `ESP_GATT_WRITE_TYPE_NO_RSP` modification. I expected the _WRITE NO RESPONSE_ packet to be different from a _WRITE_, but most likely this is not the case and the ESP just expect a response. In any case, this should not be merged and I will fix this.

**Comment by shmuelzon** [comment]
I'm not sure as I haven't read the spec about this, but I assume they're two different opcodes. Once you issue a write without response, please make sure that we still receive the `ESP_GATTC_WRITE_CHAR_EVT` so the queue won't get stuck.

**Comment by DurandA** [comment]
> I'm not sure as I haven't read the spec about this, but I assume they're two different opcodes.

You are right. According to Table 3.37 from _BLUETOOTH SPECIFICATION Version 4.2_ the opcode is `0x12` for _Write_Request_ and `0x52` for _Write_Command_. I think the Thingy:52 just accept write requests even if the descriptor say _WRITE NO RESPONSE_. I basically just bypassed the check with my patch.

What I am not sure about it that the specs also states the following about Write Command (3.4.5.3):
> No Error Response or Write Response shall be sent in response to this command.

Unfortunately, the ESP32 implementation is not open-source and I don't have a BLE sniffer around. I just expect esp_ble_gattc_write_char() to send a Write Request with `ESP_GATT_WRITE_TYPE_RSP` and a Write Request with `ESP_GATT_WRITE_TYPE_NO_RSP`.

> Once you issue a write without response, please make sure that we still receive the `ESP_GATTC_WRITE_CHAR_EVT` so the queue won't get stuck.

Sure!

**Comment by DurandA** [comment]
What style do you prefer in order to use `ESP_GATT_WRITE_TYPE_NO_RSP`?
- [ ] adding `BLE_OPERATION_TYPE_WRITE_NR` to `ble_operation_type_t`
- [ ] adding a field to `ble_operation_t`
- [ ] change `ble_operation_type_t` to a bitfield

**Comment by shmuelzon** [comment]
I’d keep it simple and add another operation type, `BLE_OPERATION_TYPE_WRITE_NR`.

**Comment by DurandA** [comment]
Please wait before merging. I cannot test it before early next week.

**Comment by DurandA** [comment]
Sorry for the delay, I was sick during the last few days. You can merge #52, it behaves as expected and `ESP_GATTC_WRITE_CHAR_EVT` is queued.

**Pull request merged**
